<?php
declare(strict_types=1);

namespace SnappyCommerce\CartLink\Controller\Load;

use Magento\Framework\App\Action\HttpGetActionInterface;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\Controller\Result\Redirect;
use Magento\Framework\Controller\Result\RedirectFactory;
use Magento\Framework\Message\ManagerInterface;
use Magento\Quote\Model\QuoteIdMaskFactory;
use Magento\Quote\Api\CartRepositoryInterface;
use Magento\Checkout\Model\Session as CheckoutSession;
use Magento\Customer\Model\Session as CustomerSession;

/**
 * Handles /cart/load?id=<masked_cart_id>
 *
 * Resolves the masked cart ID generated by the Snappy Commerce backend,
 * loads the corresponding quote into the current session, and redirects
 * the customer to the checkout page.
 */
class Index implements HttpGetActionInterface
{
    public function __construct(
        private readonly RequestInterface $request,
        private readonly RedirectFactory $redirectFactory,
        private readonly ManagerInterface $messageManager,
        private readonly QuoteIdMaskFactory $quoteIdMaskFactory,
        private readonly CartRepositoryInterface $cartRepository,
        private readonly CheckoutSession $checkoutSession,
        private readonly CustomerSession $customerSession
    ) {}

    public function execute(): Redirect
    {
        // The ?id= value is the alphanumeric Masked Quote ID from the REST API,
        // not the numeric internal entity ID.
        $maskedId = (string) $this->request->getParam('id');
        $redirect = $this->redirectFactory->create();

        if ($maskedId === '') {
            $this->messageManager->addErrorMessage(__('Invalid cart link.'));
            return $redirect->setPath('');
        }

        try {
            // Resolve masked ID → internal numeric quote ID.
            $mask = $this->quoteIdMaskFactory->create()->load($maskedId, 'masked_id');

            if (!$mask->getQuoteId()) {
                $this->messageManager->addErrorMessage(__('Cart not found.'));
                return $redirect->setPath('');
            }

            $quote = $this->cartRepository->get((int) $mask->getQuoteId());

            // Inactive quotes have already been converted to an order or have expired.
            if (!$quote->getIsActive()) {
                $this->messageManager->addErrorMessage(__('This cart is no longer available.'));
                return $redirect->setPath('');
            }

            if ($this->customerSession->isLoggedIn()) {
                // Merge the incoming guest cart into the customer's active cart.
                // Skip if it's already the same quote to avoid doubling item quantities.
                $customerQuote = $this->checkoutSession->getQuote();
                if ((int) $customerQuote->getId() !== (int) $quote->getId()) {
                    $customerQuote->merge($quote)->collectTotals();
                    $this->cartRepository->save($customerQuote);
                }
            } else {
                // For guests, write the quote ID directly to the checkout session.
                $this->checkoutSession->setQuoteId($quote->getId());
            }

            return $redirect->setPath('checkout');
        } catch (\Magento\Framework\Exception\NoSuchEntityException) {
            $this->messageManager->addErrorMessage(__('Cart not found.'));
            return $redirect->setPath('');
        } catch (\Exception) {
            $this->messageManager->addErrorMessage(__('Unable to load cart. Please try again.'));
            return $redirect->setPath('');
        }
    }
}
